### ISSUE TITLE
Write Recommendation Letter

### ISSUE THREAD

**Issue by ntrappe** [ntrappe/Education#12]
# Recommendation Letters
This Issue is for all the lovely people writing recommendation letters for me! I've added my CV, unofficial transcript, and the supervisors or labs I'm considering.

## Table of Contents
- <a href="#goals">University Goals for Rec Letters</a>
- <a href="#schools">List of Schools</a>
- <a href="#plan">Rec Letter Plan</a>
- <a href="#transcript">UCSD Transcript</a>
- <a href="#cv">Curriculum Vitae</a>
- <a href="#classes">UCSD Classes with You</a>
- <a href="#stats">Academic Stats</a>
- <a href="#topics">Research Topics of Interest</a>
- <a href="#supervisors">Potential Supervisors & Labs</a>
- [Rec Letter Suggestions](https://github.com/ntrappe/Education/issues/12#issuecomment-1763220419)
- [My Strengths](https://github.com/ntrappe/Education/issues/12#issuecomment-1771725338)

## <a href="#goals" id="goals"></a>University Goals for Rec Letters
- Intellectual Ability
- Academic Achievement
- Ability to Collaborate
- Aptitude for Research
- Evidence of Genuine Interest in Neuroscience

## <a href="#schools" id="schools"></a>Schools
| University | Deadline | Degree | Department |
| ---------- | --------- | ------- | ------ |
| Stanford   | Dec 5, 2023 | PhD | [Neuroscience](https://biosciences.stanford.edu/program-overview/) |
| UC Berkeley | Nov 27, 2023 | PhD | [Neuroscience](https://neuroscience.berkeley.edu/phd-applications/) |
| Oxford | Dec 8, 2023 | MSc + PhD | [Neuroscience](https://www.ox.ac.uk/admissions/graduate/courses/dphil-neuroscience) |
| Edinburgh | Feb 29, 2024 | MScR | [Integrative Neuroscience](https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&edition=2023&id=196) |

## <a href="#plan" id="plan"></a>Plan
| University | Stanford  | UC Berkeley | Oxford    | Edinburgh |
| ---------- | --------- | ------------ | --------- | ---------- |
| Referee 1  | Rossano  | Rossano       | Rossano  | Rossano    |
| Referee 2  | Johnson  | Johnson      | Johnson  | Johnson    |
| Referee 3  | Powell     | Powell           | Powell      | ---             |
| Referee 4  | Arthurs   | Arthurs         | ---            | ---              |
| **Status** | ✅          | ✅                 | ✅            | ✅             | 

## <a href="#transcript" id="transcript"></a>UCSD Transcript
[~Find my transcript here~.](https://github.com/ntrappe/Education/blob/main/assets/Trappe_academics.pdf)

## <a href="#cv" id="cv"></a>Curriculum Vitae
[Find my CV here.](https://github.com/ntrappe/Education/blob/main/assets/Curriculum%20Vitae.pdf)

## <a href="#classes" id="classes"></a>UCSD Classes
List shows which classes I've taken with you.
| Course | Title | Professor/TA | Term | Grade |
| ------- | ---- | ---------- | ------ | ----- | 
| [COGS 13](https://github.com/ntrappe/Education/tree/main/COGS%2013) | Field Methods | Rossano | Winter '19 | A |
| COGS 14A | Intro to Research Methods | Rossano | Winter '18 | A |
| COGS 17 | Neurobiology of Cognition | Johnson | Fall '18 | A |
| COGS 100 | Cyborgs Now & in the Future | _Arthurs_ | Fall '21 | A+ |
| [COGS 143](https://github.com/ntrappe/Education/tree/main/COGS%20143) | Animal Cognition | Johnson | Winter '19 | A+ |
| [COGS 144](https://github.com/ntrappe/Education/tree/main/COGS%20144) | Social Cognition | Rossano | Winter '22 | A+ |
| [COGS 184](https://github.com/ntrappe/Education/tree/main/COGS%20184) | Evolution of Cognition | Johnson/_Arthurs_ |  Spring '22 | A |
| [CSE 110*](https://github.com/ntrappe/Education/tree/main/CSE%20110) | Software Engineering | Powell | Winter '21 | A |
| CSE 112 | Advanced Software Engineering | Powell | Spring '22 | A |

*Tutored this course in Fall 2022

## <a href="#stats" id="stats"></a>Academic Stats
- **Overall GPA:** 3.679
- **Upper-Div GPA:** 3.826
- **Cognitive Science Classes GPA:** 4.0
- **Psychology Classes GPA:** 4.0
- **Credits Passed:** 296

## <a href="#topics" id="topics"></a>Research Topics of Interest
**`SLEEP`** **`MEMORY`** **`LEARNING`** **`DECISION-MAKING`**

## <a href="#supervisors" id="supervisors"></a>Potential Supervisors & Labs
List of the faculty members I'd consider doing research with if I went to that school.

[See the list here.](https://github.com/ntrappe/Education/issues/18)

**Comment by ntrappe** [comment]
### Suggestions 
_(From someone who was on the review board)_

- Describe yourself in the letter first
  - Who are you? What do you do? Are you in research?
  - How do you know this candidate? To what capacity?
  - Why should we care about what you say? **(Time to flex!)**
- Grad students have more weight if they're doing their defense soon
  - Note when you're submitting your dissertation or doing your defense (provide a date or month if it's set)
  - Link any of your papers
- European schools differ slightly than American schools
  - In the US, you can brag about achievements
  - In Europe, they want you to be humble (_"I was so fortunate to have had the opportunity to ..."_)
  - Some schools will reject a candidate if they don't see the magic phrase: ✨enthusiastically support✨
    - "I support this candidate applying" is OK but can be seen as not a strong enough endorsement
    - "Enthusiastically support" is a ringing endorsement and it says that you think this candidate has to apply to the school because they're a great fit

**Comment by ntrappe-msft** [comment]
## Strengths

### Research Excellence
- Proven aptitude for research demonstrated by work for the "AI for Healthy Living" and IBM Electronic Nose projects
- Recognized as detail-oriented and proficient in research activities, including literature reviews, interviews, surveys, experiment design, physical and chemical sensors, data analysis, planning, and data visualization
- Passion for research extends through various aspects of my life, from hackathons to personal projects to academic pursuits

### Self-Directed and Highly Reliable
- Demonstrated ability to work independently and self-direct research efforts
- Known for consistently meeting deadlines and delivering high-quality work without the need for constant supervision
- Proven record of taking initiative, pitching ideas, creating deliverables, and driving work, from school to my current role at Microsoft

### Broad Skill Set
- Has a diverse skill set acquired from multiple disciplines including design, art, computer science, machine learning, data science, and anthropology
- This breadth of knowledge enables me to approach problems from multiple angles and adapt to various research and laboratory settings

### Passion and Perseverance
- Unwavering love of neuroscience, as evidenced by my continuous enthusiasm, from drawing brains on whiteboards, to representing roommates as neurotransmitters, to daily discussions about neuron-related topics
- History of taking on challenges and persisting through adversity, as seen in my academic journey in computer science and athletics
- Dedicated to neuroscience through my willingness to commit to the long, rigorous PhD process

### Empathy and Ethics
- Demonstrated sense of responsibility in research, ensuring it benefits society without causing hard
- Shown an awareness for data privacy, ethical research practices, and impact of work on vulnerable communities
- Exhibited a passion for promoting diversity and inclusion, demonstrated through my actions at UCSD and campaign at Microsoft to address gender parity
- As a tutor, actively supported students' well-being, academic growth, different learning styles, and showed compassion


_I was asked to outline what I think is important to include in my letters and what I see as my strengths. I'm happy to elaborate on any of the points if needed. This isn't a complete list, but they're the things I value the most about myself._

**Comment by ntrappe** [comment]
## Strengths

### Research Excellence
- Proven aptitude for research demonstrated by work for the "AI for Healthy Living" and IBM Electronic Nose projects
- Recognized as detail-oriented and proficient in research activities, including literature reviews, interviews, surveys, experiment design, physical and chemical sensors, data analysis, planning, and data visualization
- Passion for research extends through various aspects of my life, from hackathons to personal projects to academic pursuits

### Self-Directed and Highly Reliable
- Demonstrated ability to work independently and self-direct research efforts
- Known for consistently meeting deadlines and delivering high-quality work without the need for constant supervision
- Proven record of taking initiative, pitching ideas, creating deliverables, and driving work, from school to my current role at Microsoft

### Broad Skill Set
- Has a diverse skill set acquired from multiple disciplines including design, art, computer science, machine learning, data science, and anthropology
- This breadth of knowledge enables me to approach problems from multiple angles and adapt to various research and laboratory settings

### Passion and Perseverance
- Unwavering love of neuroscience, as evidenced by my continuous enthusiasm, from drawing brains on whiteboards, to representing roommates as neurotransmitters, to daily discussions about neuron-related topics
- History of taking on challenges and persisting through adversity, as seen in my academic journey in computer science and athletics
- Dedicated to neuroscience through my willingness to commit to the long, rigorous PhD process

### Empathy and Ethics
- Demonstrated sense of responsibility in research, ensuring it benefits society without causing hard
- Shown an awareness for data privacy, ethical research practices, and impact of work on vulnerable communities
- Exhibited a passion for promoting diversity and inclusion, demonstrated through my actions at UCSD and campaign at Microsoft to address gender parity
- As a tutor, actively supported students' well-being, academic growth, different learning styles, and showed compassion


_I was asked to outline what I think is important to include in my letters and what I see as my strengths. I'm happy to elaborate on any of the points if needed. This isn't a complete list, but they're the things I value the most about myself._
