### ISSUE TITLE
UWash

### ISSUE THREAD

**Issue by ntrappe** [ntrappe/Education#8]
### PhD Neuroscience

| Deadline         | Cost | Portal               |
| ------------- | ----- | -------------- |
| November 28 | $85  | [`Open App`](https://apply.grad.uw.edu/portal/gr_app) |

**Requirements:**
- [ ] Transcripts from all universities attended
- [ ] Submit names/emails of recommenders
- [ ] CV (with research experience, presentations, publications)
- [ ] Short answers

**Short Answer Prompts:**
  - [ ] Please list your research experiences in bullet points, including summer research internships, academic year research, post-baccalaureate, and/or work-related experiences. (2,000 char).
  - [ ] How many total months of research experience do you have?  (20 hours per week for 1 year = 6 months full-time). The answer box will only take integers. List in Full Time Months.
  - [ ] Tell us about your most interesting or rewarding research experience in a lab environment. (3,000 char).
  - [ ] Why do you want to pursue a Ph.D. in Neuroscience? (2,000 char).
  - [ ] Why do you want to attend the University of Washington? (2,000 char).
  - [ ] What does Diversity, Equity, and Inclusion mean to you? What can be done to improve Diversity, Equity, and Inclusion in science and society? (2,000 char).
  - [ ] Describe a time you navigated a challenging obstacle, scientific or otherwise. (2,000 char)
  - [ ] Which University of Washington Neuroscience research labs particularly interest you and why? Please discuss at least three (3) labs. (3,000 char)
  - [ ] _Optional: Is there anything else relevant to your application that you would like to share that was not covered in the questions above? (2,500 char)._

**Faculty Interviews:**
While not mandatory, you have the opportunity to list any specific faculty members you would be interested in discussing with during the interview process. If you so choose, please explain your reasons for selecting these faculty members. You may use [our faculty list](http://depts.washington.edu/neurogrd/people/faculty/) to find the list of all faculty members.

**Comment by ntrappe-msft** [comment]
### Interviewee
- Worked at UCSF lab with mice (depression)
- Decided on a lab by (1) environment, (2) research interest, and (3) PI

### University
- Neuroscience is not a department but a program
- First year funding covered by Neuroscience
- $3400/month gross income
- Qualifier at the end of 2nd year

### Labs
- 3 rotations, 1x quarter
- You email PIs and set up your rotations if there's room

### People
- Horacio Iglesias (sleep)
- Sam Golden (ML for behavior)
- David Baker (biochemistry)

**Comment by ntrappe** [comment]
Abandoned. Needed to cut 1 school from the list.
